### ISSUE TITLE
Typing Error on createSpyObj on a Service

### ISSUE THREAD

**Issue by Calidus** [FDIM/jasmine-unit-test-generator#2]
I was testing out this library(thanks for your hard work by the way), and I believe I ran across a small bug. I ran the generate script on a component that uses ActivatedRoute.
`  constructor(private route: ActivatedRoute, private messageService: MessageService) {    }`
`this.route.params.pipe(take(1)).subscribe((params) => {// do stuff})`

The tooling generated the following code, which fails to compile due to a typing error:

`fakeRoute = jasmine.createSpyObj<ActivatedRoute>('ActivatedRoute', ['']);`

I believe it should be:

`fakeRoute = jasmine.createSpyObj<ActivatedRoute>('ActivatedRoute', []);`

I believe this happens whenever you inject a service but don't call any methods on that service.

**Comment by FDIM** [comment]
Yep, you're spot on. I've seen it at work - I'll test it out and see if empty array works

Also, I have a plan to add a custom dependency handler for router so that extra code for handling router events, params, query params etc would come out of the box

**Comment by FDIM** [comment]
Fixed in 1.2.1

Thanks for reporting the issue :)

**Comment by FDIM** [comment]
@Calidus just an FYI - jasmine requires a non-empty array at runtime.

I have no-idea what is better,  `jasmine.createSpyObj<ActivatedRoute>('ActivatedRoute', []);` make TS happy but breaks at runtime :/

**Comment by Calidus** [comment]
Sounds like that is bug in the index.d.ts file of @types/jasmine.
